# Root directory where all pipeline artifacts will be stored
# (datasets, intermediate outputs, models, metrics, etc.)
artifacts_root: artifacts


# =========================
# Data Ingestion Stage
# =========================
data_ingestion:

  # Directory for all data-ingestionâ€“related artifacts
  # Example: downloaded zip, extracted files
  root_dir: artifacts/data_ingestion


  # Public URL from where the raw dataset is downloaded
  # This should be a *direct downloadable* link (GitHub raw URL, S3, etc.)
  source_URL: https://github.com/Shivanshvyas1729/All-Datasets-is-here/raw/refs/heads/main/Chicken-fecal-images.zip

              
  # Local path where the downloaded ZIP file will be saved
  # Used by the ingestion script to store the raw compressed data
  local_data_file: artifacts/data_ingestion/data.zip


  # Directory where the ZIP file will be extracted
  # Final CSV files will be available here after unzip
  unzip_dir: artifacts/data_ingestion


#  Hierarchical Data Format v5
prepare_base_model:
  root_dir: artifacts/prepare_base_model 
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path :  artifacts/prepare_base_model/base_model_updated.h5



training:
  root_dir: artifacts/training

  trained_model_path: artifacts/training/model.h5
  